{% set version = "11.3.1" %}
{% set build = 0 %}

package:
  name: cudatoolkit-dummy
  version: {{ version }}

build:
  number: {{ build }}

outputs:
  - name: cudatoolkit
    string: dummy_{{ build }}

about:
  license: MIT
  summary: 'Dummy package for cudatoolkit'