{% set name = "openmm" %}
{% set version = "8.5.1" %}
{% set build = 2 %}
{% set cuda_version_min = "12.0" %} # 12.0 is the minimal CUDA version that works with conda-forge repo
{% set cuda_version_max = "13" %} # package built with CUDA 12.0 should work with CUDA 12.x

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/z-gong/{{ name }}.git
  git_branch: 8.5.1_fix

build:
  number: {{ build }}
  string: fix_barostat_{{ build }}

requirements:
  build:
    - python
    - cython
    - numpy
    - swig
    - doxygen
    - cmake
    - make
    - gxx
    - cuda-version {{ cuda_version_min }}
    - cuda-compiler
    - cuda-nvrtc-dev
    - cuda-profiler-api
    - libcufft-dev

  run:
    - python
    - numpy
    - cuda-version >={{ cuda_version_min }},<{{ cuda_version_max }}
    - cuda-cudart
    - cuda-nvrtc
    - libcufft

about:
  home: http://openmm.org
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - docs-source/licenses/Licenses.txt
    - docs-source/licenses/LGPL.txt
    - docs-source/licenses/GPL.txt
  summary: A high performance toolkit for molecular simulation, with barostat patched.

  description: |
    OpenMM is a toolkit for molecular simulation. It can be used either as a
    stand-alone application for running simulations, or as a library you call
    from your own code. It provides a combination of extreme flexibility
    (through custom forces and integrators), openness, and high performance
    (especially on recent GPUs) that make it truly unique among simulation
    codes. OpenMM is MIT licensed with some LGPL portions (CUDA and OpenCL
    platforms).
  doc_url: http://docs.openmm.org
  dev_url: https://github.com/z-gong/openmm/tree/8.5.1_fix
