{% set name = "openmm" %}
{% set version = "8.1.2" %}
{% set build = 0 %}
{% set cuda_version = "12.0" %} # 12.0 is the minimal CUDA version that works with conda-forge repo

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/z-gong/{{ name }}.git
  git_branch: 8.1.2_fix

build:
  number: {{ build }}
  string: fix_barostat_{{ build }}

requirements:
  build:
    - python
    - cython
    - numpy <2
    - swig
    - doxygen
    - cmake
    - make
    - gxx
    - cuda-version {{ cuda_version }}
    - cuda-compiler
    - cuda-nvrtc-dev
    - cuda-profiler-api
    - libcufft-dev

  run:
    - python
    - numpy <2
    - cuda-version {{ cuda_version }}
    - cuda-cudart
    - cuda-nvrtc
    - libcufft
about:
  home: http://openmm.org
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - docs-source/licenses/Licenses.txt
    - docs-source/licenses/LGPL.txt
    - docs-source/licenses/GPL.txt
  summary: A high performance toolkit for molecular simulation, with barostat patched.

  description: |
    OpenMM is a toolkit for molecular simulation. It can be used either as a
    stand-alone application for running simulations, or as a library you call
    from your own code. It provides a combination of extreme flexibility
    (through custom forces and integrators), openness, and high performance
    (especially on recent GPUs) that make it truly unique among simulation
    codes. OpenMM is MIT licensed with some LGPL portions (CUDA and OpenCL
    platforms).
  doc_url: http://docs.openmm.org
  dev_url: https://github.com/z-gong/openmm/tree/8.1.2_fix
